package recording

//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetServiceCapabilities
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetServiceCapabilitiesResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateRecording
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateRecordingResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteRecording
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteRecordingResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordings
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingsResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateTrack
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateTrackResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteTrack
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteTrackResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetTrackConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetTrackConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetTrackConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetTrackConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateRecordingJob
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording CreateRecordingJobResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteRecordingJob
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording DeleteRecordingJobResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobs
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobsResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingJobConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingJobConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobConfiguration
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobConfigurationResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingJobMode
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording SetRecordingJobModeResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobState
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingJobStateResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingOptions
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetRecordingOptionsResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording ExportRecordedData
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording ExportRecordedDataResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording StopExportRecordedData
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording StopExportRecordedDataResponse
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetExportRecordedDataState
//go:generate go run github.com/waynejared/onvif/sdk/codegen recording recording GetExportRecordedDataStateResponse
